version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: citypay_ims
      POSTGRES_PASSWORD: C!typ@y123#
      POSTGRES_DB: citypay_ims
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres-db-project/init.sql:/docker-entrypoint-initdb.d/init.sql

  flask-app:
    build: ./flask-app
    ports:
      - "1451:1451"
    env_file:
      - ./flask-app/.env
    depends_on:
      - db

volumes:
  db_data: