version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: citypay_ims
      POSTGRES_PASSWORD: C!typ@y123#
      POSTGRES_DB: citypay_ims
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql